"""WebSocket commands for the finance Area.

Panel registration and WebSocket API for personal finance tracking.

This module provides the frontend panel and all WebSocket command handlers
for the Ha Finance custom component. It enables personal finance tracking
within Home Assistant, including account management, transaction recording,
recurring plan scheduling, and analytics.

WebSocket Commands
------------------
All commands use the ``ha_finance/`` prefix and are sent via the Home
Assistant WebSocket API.

**Account Query**
    - ``ha_finance/accounts`` -- List all accounts.
    - ``ha_finance/account`` -- Get single account with transactions and plans.

**Transaction CRUD**
    - ``ha_finance/add_transaction`` -- Record a new transaction.
    - ``ha_finance/update_transaction`` -- Modify an existing transaction.
    - ``ha_finance/delete_transaction`` -- Remove a transaction.

**Recurring Plan CRUD**
    - ``ha_finance/add_plan`` -- Create a recurring plan.
    - ``ha_finance/update_plan`` -- Modify a recurring plan.
    - ``ha_finance/delete_plan`` -- Remove a recurring plan.

**Analytics**
    - ``ha_finance/chart_data`` -- Income vs. expenses chart data by month.

**Account Management**
    - ``ha_finance/add_account`` -- Create a new account (config entry).
    - ``ha_finance/update_account`` -- Rename or annotate an account.
    - ``ha_finance/delete_account`` -- Delete an account and its config entry.

Permission Model
----------------
ALL commands are public -- no admin privileges are required. This is an
important distinction from other Home Assistant components that restrict
certain operations to administrators.

Frequency Options
-----------------
Recurring plans support the following frequency values:
    - ``daily``
    - ``weekly``
    - ``monthly``
    - ``yearly``

Day Constraints
---------------
    - For ``monthly`` and ``yearly`` frequencies, ``day`` must be 1--28.
    - For ``weekly`` frequency, ``day`` must be 1--7 (Monday--Sunday).

Home Assistant Bus Events
-------------------------
The following events are fired on the HA event bus by this component:
    - ``ha_finance_transaction_added`` -- A new transaction was recorded.
    - ``ha_finance_recurring_executed`` -- A recurring plan produced a transaction.
    - ``ha_finance_balance_adjusted`` -- An account balance was adjusted.
    - ``ha_finance_low_balance`` -- An account balance dropped below threshold.

Transaction Types
-----------------
    - ``manual`` -- Created by the user through the UI or API.
    - ``recurring`` -- Auto-generated by a recurring plan.
    - ``adjustment`` -- Balance correction or adjustment entry.
"""
from __future__ import annotations

import logging
import time
from typing import TYPE_CHECKING, Any

import voluptuous as vol

from homeassistant.components import websocket_api
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import device_registry as dr

from .const import (
    CONF_ACCOUNT_ID,
    CONF_ACCOUNT_NAME,
    CONF_INITIAL_BALANCE,
    DOMAIN,
    FREQUENCY_DAILY,
    FREQUENCY_MONTHLY,
    FREQUENCY_OPTIONS,
    FREQUENCY_WEEKLY,
    FREQUENCY_YEARLY,
    TRANSACTION_MANUAL,
)
from ...const import device_id
from ...runtime import get_data
from .area import FinanceArea, generate_account_id
from .const import AREA
from .coordinator import FinanceCoordinator, get_coordinator_for_account
from .models import RecurringPlan, Transaction


if TYPE_CHECKING:
    from .store import FinanceStore

_LOGGER = logging.getLogger(__name__)

@callback
def async_register_websocket_commands(hass: HomeAssistant) -> None:
    """Register the finance Area's WebSocket commands."""
    for command in (
        ws_get_accounts,
        ws_get_account,
        ws_add_transaction,
        ws_update_transaction,
        ws_delete_transaction,
        ws_add_plan,
        ws_update_plan,
        ws_delete_plan,
        ws_get_chart_data,
        ws_add_account,
        ws_update_account,
        ws_delete_account,
    ):
        websocket_api.async_register_command(hass, command)


def _area(hass: HomeAssistant) -> FinanceArea:
    """Return the finance Area."""
    return get_data(hass).finance


def _get_store(hass: HomeAssistant) -> FinanceStore:
    """Return the shared finance store."""
    return _area(hass).store


# WebSocket Handlers

@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/accounts",
    }
)
@websocket_api.async_response
async def ws_get_accounts(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/accounts`` -- list all accounts.

    WebSocket command
        ``ha_finance/accounts``

    Parameters
        None.

    Returns
        dict: ``{accounts: [{id, name, balance, notes}, ...]}``
            A list of every registered account with its current balance.
    """
    store = _get_store(hass)
    await store.async_load()

    accounts = [
        {
            "id": account.id,
            "name": account.name,
            "balance": account.balance,
            "notes": account.notes,
        }
        for account in store.data.accounts.values()
    ]

    connection.send_result(msg["id"], {"accounts": accounts})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/account",
        vol.Required("account_id"): str,
    }
)
@websocket_api.async_response
async def ws_get_account(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/account`` -- get a single account with full details.

    WebSocket command
        ``ha_finance/account``

    Parameters
        account_id (str): The unique identifier of the account.

    Returns
        dict: ``{account: {id, name, balance, notes, transactions: [...],
        recurring_plans: [...]}}``
            The account object including its full transaction history and
            all associated recurring plans.

    Errors
        ``not_found`` -- No account exists with the given *account_id*.
    """
    store = _get_store(hass)
    await store.async_load()

    account = store.data.get_account(msg["account_id"])
    if account is None:
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    result = {
        "account": {
            "id": account.id,
            "name": account.name,
            "balance": account.balance,
            "notes": account.notes,
            "transactions": [tx.to_dict() for tx in account.transactions],
            "recurring_plans": {
                plan_id: plan.to_dict()
                for plan_id, plan in account.recurring_plans.items()
            },
        }
    }

    connection.send_result(msg["id"], result)


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/add_transaction",
        vol.Required("account_id"): str,
        vol.Required("amount"): vol.Coerce(float),
        vol.Optional("note", default=""): str,
        vol.Optional("transaction_type", default=TRANSACTION_MANUAL): str,
    }
)
@websocket_api.async_response
async def ws_add_transaction(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/add_transaction`` -- record a new transaction.

    WebSocket command
        ``ha_finance/add_transaction``

    Parameters
        account_id (str): The account to add the transaction to.
        amount (float): Transaction amount (positive for income, negative
            for expenses).
        note (str, optional): Descriptive note. Defaults to ``""``.
        transaction_type (str, optional): One of ``manual``, ``recurring``,
            or ``adjustment``. Defaults to ``"manual"``.

    Returns
        dict: ``{transaction: {...}, balance: float}``
            The newly created transaction object and the updated account
            balance.

    Side Effects
        - Fires the ``ha_finance_transaction_added`` event on the HA bus.
        - Updates the account balance sensor entity.

    Errors
        ``not_found`` -- No account exists with the given *account_id*.
        ``error`` -- Transaction creation failed.
    """
    coordinator = get_coordinator_for_account(hass, msg["account_id"])
    transaction: Transaction | None = None

    if coordinator is None:
        # Fall back to direct store access
        store = _get_store(hass)
        await store.async_load()
        account = store.data.get_account(msg["account_id"])
        if account is None:
            connection.send_error(msg["id"], "not_found", "Account not found")
            return

        transaction = Transaction.create(
            amount=msg["amount"],
            note=msg["note"],
            transaction_type=msg["transaction_type"],
        )
        account.add_transaction(transaction)
        await store.async_save()
    else:
        transaction = await coordinator.async_add_transaction(
            amount=msg["amount"],
            note=msg["note"],
            transaction_type=msg["transaction_type"],
        )

    if transaction is None:
        connection.send_error(msg["id"], "error", "Failed to create transaction")
        return

    connection.send_result(
        msg["id"],
        {"success": True, "transaction": transaction.to_dict()},
    )


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/update_transaction",
        vol.Required("account_id"): str,
        vol.Required("transaction_id"): str,
        vol.Optional("amount"): vol.Coerce(float),
        vol.Optional("note"): str,
    }
)
@websocket_api.async_response
async def ws_update_transaction(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/update_transaction`` -- modify an existing transaction.

    WebSocket command
        ``ha_finance/update_transaction``

    Parameters
        account_id (str): The account that owns the transaction.
        transaction_id (str): The unique identifier of the transaction.
        amount (float, optional): New transaction amount. If provided, the
            account balance is adjusted by the difference between the new
            and old amounts.
        note (str, optional): New descriptive note.

    Returns
        dict: The updated transaction object (``{success: true}``).

    Side Effects
        - Adjusts the account balance if *amount* is changed.
        - Refreshes the coordinator and sensor entities.

    Errors
        ``not_found`` -- Account or transaction not found.
    """
    store = _get_store(hass)
    await store.async_load()

    account = store.data.get_account(msg["account_id"])
    if account is None:
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    # Find and update transaction
    transaction = None
    for tx in account.transactions:
        if tx.id == msg["transaction_id"]:
            transaction = tx
            break

    if transaction is None:
        connection.send_error(msg["id"], "not_found", "Transaction not found")
        return

    # Update balance if amount changed
    if "amount" in msg:
        old_amount = transaction.amount
        new_amount = msg["amount"]
        account.balance += (new_amount - old_amount)
        transaction.amount = new_amount

    if "note" in msg:
        transaction.note = msg["note"]

    await store.async_save()

    # Refresh coordinator if available
    coordinator = get_coordinator_for_account(hass, msg["account_id"])
    if coordinator:
        await coordinator.async_refresh()

    connection.send_result(msg["id"], {"success": True})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/delete_transaction",
        vol.Required("account_id"): str,
        vol.Required("transaction_id"): str,
    }
)
@websocket_api.async_response
async def ws_delete_transaction(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/delete_transaction`` -- remove a transaction.

    WebSocket command
        ``ha_finance/delete_transaction``

    Parameters
        account_id (str): The account that owns the transaction.
        transaction_id (str): The unique identifier of the transaction to
            delete.

    Returns
        dict: ``{success: true}``

    Side Effects
        - Reverses the balance change that the deleted transaction
          originally caused.
        - Refreshes the coordinator and sensor entities.

    Errors
        ``not_found`` -- Account or transaction not found.
    """
    store = _get_store(hass)
    await store.async_load()

    account = store.data.get_account(msg["account_id"])
    if account is None:
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    # Find and remove transaction
    transaction = None
    for i, tx in enumerate(account.transactions):
        if tx.id == msg["transaction_id"]:
            transaction = tx
            account.transactions.pop(i)
            break

    if transaction is None:
        connection.send_error(msg["id"], "not_found", "Transaction not found")
        return

    # Reverse the balance change
    account.balance -= transaction.amount
    await store.async_save()

    # Refresh coordinator if available
    coordinator = get_coordinator_for_account(hass, msg["account_id"])
    if coordinator:
        await coordinator.async_refresh()

    connection.send_result(msg["id"], {"success": True})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/add_plan",
        vol.Required("account_id"): str,
        vol.Required("title"): str,
        vol.Required("amount"): vol.Coerce(float),
        vol.Required("frequency"): vol.In(FREQUENCY_OPTIONS),
        vol.Required("day"): vol.All(vol.Coerce(int), vol.Range(min=1, max=28)),
        vol.Optional("month", default=1): vol.All(vol.Coerce(int), vol.Range(min=1, max=12)),
        vol.Optional("active", default=True): bool,
    }
)
@websocket_api.async_response
async def ws_add_plan(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/add_plan`` -- create a recurring plan.

    WebSocket command
        ``ha_finance/add_plan``

    Parameters
        account_id (str): The account to attach the plan to.
        title (str): Human-readable name for the recurring plan.
        amount (float): Transaction amount applied on each recurrence.
        frequency (str): One of ``daily``, ``weekly``, ``monthly``, or
            ``yearly``.
        day (int): Day of recurrence (1--28). For ``weekly`` frequency,
            represents the weekday (1--7).
        month (int, optional): Month of recurrence (1--12). Only relevant
            for ``yearly`` frequency. Defaults to ``1``.
        active (bool, optional): Whether the plan is active on creation.
            Defaults to ``true``.

    Returns
        dict: ``{plan: {...}}``
            The newly created recurring plan object including its
            generated ``plan_id``.

    Errors
        ``not_found`` -- No account exists with the given *account_id*.
    """
    import uuid

    coordinator = get_coordinator_for_account(hass, msg["account_id"])
    plan_id = f"plan_{uuid.uuid4().hex[:8]}"

    if coordinator is None:
        # Fall back to direct store access
        store = _get_store(hass)
        await store.async_load()
        account = store.data.get_account(msg["account_id"])
        if account is None:
            connection.send_error(msg["id"], "not_found", "Account not found")
            return
        plan = RecurringPlan(
            id=plan_id,
            title=msg["title"],
            amount=msg["amount"],
            frequency=msg["frequency"],
            day=msg["day"],
            month=msg.get("month", 1),
            active=msg.get("active", True),
        )
        account.add_recurring_plan(plan)
        await store.async_save()
    else:
        await coordinator.async_add_recurring_plan(
            plan_id=plan_id,
            title=msg["title"],
            amount=msg["amount"],
            frequency=msg["frequency"],
            day=msg["day"],
            month=msg["month"],
            active=msg["active"],
        )

    connection.send_result(msg["id"], {"success": True, "plan_id": plan_id})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/update_plan",
        vol.Required("account_id"): str,
        vol.Required("plan_id"): str,
        vol.Optional("title"): str,
        vol.Optional("amount"): vol.Coerce(float),
        vol.Optional("frequency"): vol.In(FREQUENCY_OPTIONS),
        vol.Optional("day"): vol.All(vol.Coerce(int), vol.Range(min=1, max=28)),
        vol.Optional("month"): vol.All(vol.Coerce(int), vol.Range(min=1, max=12)),
        vol.Optional("active"): bool,
    }
)
@websocket_api.async_response
async def ws_update_plan(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/update_plan`` -- modify a recurring plan.

    WebSocket command
        ``ha_finance/update_plan``

    Parameters
        account_id (str): The account that owns the plan.
        plan_id (str): The unique identifier of the plan.
        title (str, optional): New plan title.
        amount (float, optional): New recurrence amount.
        frequency (str, optional): New frequency (``daily``, ``weekly``,
            ``monthly``, or ``yearly``).
        day (int, optional): New day of recurrence (1--28, or 1--7 for
            weekly).
        month (int, optional): New month of recurrence (1--12).
        active (bool, optional): Enable or disable the plan.

    Returns
        dict: The updated recurring plan object (``{success: true}``).

    Errors
        ``not_found`` -- Account or plan not found.
    """
    coordinator = get_coordinator_for_account(hass, msg["account_id"])

    # Extract update fields
    update_fields = {}
    for field in ["title", "amount", "frequency", "day", "month", "active"]:
        if field in msg:
            update_fields[field] = msg[field]

    if coordinator is None:
        # Fall back to direct store access
        store = _get_store(hass)
        await store.async_load()
        account = store.data.get_account(msg["account_id"])
        if account is None:
            connection.send_error(msg["id"], "not_found", "Account not found")
            return
        plan = account.recurring_plans.get(msg["plan_id"])
        if plan is None:
            connection.send_error(msg["id"], "not_found", "Plan not found")
            return
        for key, value in update_fields.items():
            setattr(plan, key, value)
        await store.async_save()
    else:
        await coordinator.async_update_recurring_plan(msg["plan_id"], **update_fields)

    connection.send_result(msg["id"], {"success": True})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/delete_plan",
        vol.Required("account_id"): str,
        vol.Required("plan_id"): str,
    }
)
@websocket_api.async_response
async def ws_delete_plan(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/delete_plan`` -- remove a recurring plan.

    WebSocket command
        ``ha_finance/delete_plan``

    Parameters
        account_id (str): The account that owns the plan.
        plan_id (str): The unique identifier of the plan to delete.

    Returns
        dict: ``{success: true}``

    Side Effects
        - Removes associated plan sensor entities from Home Assistant.

    Errors
        ``not_found`` -- Account or plan not found.
    """
    coordinator = get_coordinator_for_account(hass, msg["account_id"])

    if coordinator is None:
        # Fall back to direct store access
        store = _get_store(hass)
        await store.async_load()
        account = store.data.get_account(msg["account_id"])
        if account is None:
            connection.send_error(msg["id"], "not_found", "Account not found")
            return
        account.remove_recurring_plan(msg["plan_id"])
        await store.async_save()
    else:
        await coordinator.async_remove_recurring_plan(msg["plan_id"])

    connection.send_result(msg["id"], {"success": True})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/chart_data",
        vol.Required("account_id"): str,
        vol.Optional("months", default=6): vol.Coerce(int),
    }
)
@websocket_api.async_response
async def ws_get_chart_data(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Handle ``ha_finance/chart_data`` -- income vs. expenses analytics.

    WebSocket command
        ``ha_finance/chart_data``

    Parameters
        account_id (str): The account to generate chart data for.
        months (int, optional): Number of recent months to include.
            Defaults to ``6``.

    Returns
        dict: ``{chart_data: [{month, income, expenses}, ...]}``
            A list of monthly aggregates sorted oldest-first. Income and
            expense amounts are rounded to 2 decimal places.

    Errors
        ``not_found`` -- No account exists with the given *account_id*.
    """
    from datetime import datetime
    from collections import defaultdict

    store = _get_store(hass)
    await store.async_load()

    account = store.data.get_account(msg["account_id"])
    if account is None:
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    # Group transactions by month
    months_data: dict[str, dict[str, float]] = defaultdict(
        lambda: {"income": 0.0, "expenses": 0.0}
    )

    for tx in account.transactions:
        try:
            tx_date = datetime.fromisoformat(tx.timestamp)
            month_key = tx_date.strftime("%Y-%m")

            if tx.amount >= 0:
                months_data[month_key]["income"] += tx.amount
            else:
                months_data[month_key]["expenses"] += abs(tx.amount)
        except (ValueError, TypeError):
            continue

    # Sort by month and limit to requested number
    sorted_months = sorted(months_data.keys(), reverse=True)[: msg["months"]]
    sorted_months.reverse()  # Oldest first for chart

    chart_data = [
        {
            "month": month,
            "income": round(months_data[month]["income"], 2),
            "expenses": round(months_data[month]["expenses"], 2),
        }
        for month in sorted_months
    ]

    connection.send_result(msg["id"], {"data": chart_data})


# Account Management WebSocket Handlers

@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/add_account",
        vol.Required("name"): str,
        vol.Optional("initial_balance", default=0.0): vol.Coerce(float),
    }
)
@websocket_api.async_response
async def ws_add_account(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Create an Account.

    This used to start a config flow and wait for the entry to be set up. An
    Account is a store record now (ADR-0001), so it is a write.
    """
    name = msg["name"].strip()
    if not name:
        connection.send_error(msg["id"], "invalid_name", "Account name cannot be empty")
        return

    area = _area(hass)
    for existing in area.store.data.accounts.values():
        if existing.name.lower() == name.lower():
            connection.send_error(
                msg["id"], "duplicate_name", f"Account '{name}' already exists"
            )
            return

    account_id = generate_account_id(name)
    if area.get(account_id) is not None:
        connection.send_error(
            msg["id"], "duplicate_id", f"Account id '{account_id}' already exists"
        )
        return

    await area.async_add_account(account_id, name, msg["initial_balance"])
    connection.send_result(
        msg["id"],
        {"account_id": account_id, "name": name, "balance": msg["initial_balance"]},
    )


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/update_account",
        vol.Required("account_id"): str,
        vol.Optional("name"): str,
        vol.Optional("low_balance_threshold"): vol.Coerce(float),
    }
)
@websocket_api.async_response
async def ws_update_account(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Rename an Account or change its low-balance threshold."""
    area = _area(hass)
    account = area.store.data.get_account(msg["account_id"])
    if account is None:
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    if "name" in msg:
        new_name = msg["name"].strip()
        if not new_name:
            connection.send_error(
                msg["id"], "invalid_name", "Account name cannot be empty"
            )
            return
        account.name = new_name

        device_reg = dr.async_get(hass)
        device = device_reg.async_get_device(
            identifiers={(DOMAIN, device_id(AREA, msg["account_id"]))}
        )
        if device:
            device_reg.async_update_device(device.id, name=new_name)

    await area.store.async_save()

    coordinator = area.get(msg["account_id"])
    if coordinator is not None:
        await coordinator.async_refresh()

    connection.send_result(msg["id"], {"success": True})


@websocket_api.websocket_command(
    {
        vol.Required("type"): "woow_ha_records/finance/delete_account",
        vol.Required("account_id"): str,
    }
)
@websocket_api.async_response
async def ws_delete_account(
    hass: HomeAssistant,
    connection: websocket_api.ActiveConnection,
    msg: dict[str, Any],
) -> None:
    """Delete an Account and everything recorded against it."""
    if not await _area(hass).async_remove_account(msg["account_id"]):
        connection.send_error(msg["id"], "not_found", "Account not found")
        return

    connection.send_result(msg["id"], {"success": True})
